#!/usr/bin/env python
# -*- coding: utf-8 -*-

from superPkg.lib import type_it
import argparse

description = 'stkrgcp_description'
parser = argparse.ArgumentParser(description=description)
parser.add_argument('--text',
                    type=str,
                    nargs='+',
                    help='Type some text',
                    required=False)

args = parser.parse_args()
text = args.text

type_it(text)
